//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravelJournal.PCL.DataService
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using TravelJournal.PCL.BusinessLogic;

	public interface IPhotoManager 
	{
        bool FoundRawPhoto(DateTime tag, Action<Photo> onPhotoFoundHandler);
	}
}

