//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravelJournal.PCL.DataService
{
	using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TravelJournal.PCL.BusinessLogic;
   

	public interface IWebService 
	{
		GpsPoint GetUserPosition();
        GpsPosition GetGeoposition(GpsPoint coordinate);
	}
}

